### ISSUE TITLE
process for migrating a repo to ivoa-std

### ISSUE THREAD

**Issue by pdowler** [ivoa-std/ivoatexDoc#2]
Having performed a few of these and seeing what can happen, I still think there are  some things to improve.

The doc-template can only really provide some default files that the original-repo does not: probably README.md and LICENSE and maybe a default workflow (have to check), which leads to two complications for the ivoa-std maintainer doing the migration:
1. if the original-repo already has these files a merge needs to be done
2. github supports and people are using either README.md and README.rst (yay, more markup langs); if you have both, the README.md seems to be the one github displays by default

So, that is a pain and probably makes the template mechanism offer so little that we should instead just require that the original-repo have a decent README and the LICENSE before going ahead with the migration. That also means that the author(s) have added the LICENSE themselves before hand, rather than it being implicitly added by the request to migrate, which I consider a good thing.

So, I propose to modify the migration process in this section to be something like:
1. check that original-repo has the minimum required files (README and LICENSE)
2. create repository ivoa-std/<short-name> using github import mechanism
3. setup github workflow (if not included in import)
4. setup branch protection rules
5. give WG team and editor the following privileges: maintainer role
6. notify WG and editor that migration is complete

Thoughts?

**Comment by mbtaylor** [comment]
I haven't thought very deeply about this but: sounds reasonable.

**Comment by Zarquan** [comment]
Yep, avoiding a merge at the start is good.

**Comment by molinaro-m** [comment]
I agree.
I wonder if we should write the checklist at step 1 explicitly so that the maintainer of ivoa-std, in view of migrating the repo:
- checks the README
- checks the LICENSE
- runs a make 
- (other things to check?)
before creating the ivoa-std bare repo and go on from step 2.

I know, this should be common and understood, but I feel a complete checklist would be better.

**Comment by msdemlei** [comment]
Hi Pat,

On Wed, Mar 02, 2022 at 10:33:14AM -0800, Patrick Dowler wrote:
> So, that is a pain and probably makes the template mechanism offer
> so little that we should instead just require that the
> original-repo have a decent README and the LICENSE before going
> ahead with the migration. That also means that the author(s) have
> added the LICENSE themselves before hand, rather than it being
> implicitly added by the request to migrate.

Agreed.  I'd say I'll add template files for both to ivoatex (unless
someone beats me to it).

> So, I propose to modify the migration process in this section to be something like:
> 1. check that original-repo has the minimum required files (README and LICENSE)

Frankly: I'd say "check it out and see if it builds".  I'd have a few
more checklist items for which I'd do a later PR.

> 2. create repository ivoa-std/<short-name> using github import mechanism
> 3. setup github workflow (if not included in import)

ivoatex has a make target that writes CI recipes, but I'd say you
should leave that to the editor.  For one, their particular case may
need some extra twist, and of a second, I'm not convinced having this
CI thing on all the documents is a good idea -- for many reasons, but
most importantly: someone would have to manage all those CI recipes
(they *will* regularly break), and we don't want to waste our
editors' times with that.

Editors who want the CI can set it up themselves using a simple
command (and will have to update it, etc, as per regular
announcements on docstd).  The others, I argue, will be fine the way
we've worked so far, with occasional builds on the doc repo or
somewhere else outside of github.

*If* we really want a repo of bleeding-edge builds (and I wouldn't
know why), I'd offer to write something that would do these builds
without spinning up VMs, on one (public) piece of infrastructure for
all the repos, and delivery through public infrastructure.

> 4. setup branch protection rules
> 5. give WG team and editor the following privileges: maintainer role
> 6. notify WG and editor that migration is complete

plus: Tell the editor to rename their original repo and fork the one
from ivoa-tex.

**Comment by pdowler** [comment]
OK, will write thus up early next week.

**Comment by msdemlei** [comment]
Since Mark has checked the instructions and considered them fine, I'll close this.

The template thing is, I claim, reasonably addressed by ivoatex PR 72 and PR #3.  Reviewers for both would be welcome, but keeping this bug open probably won't help that.
