### ISSUE TITLE
How to identify commit from published document?

### ISSUE THREAD

**Issue by mbtaylor** [ivoa-std/ivoatexDoc#42]
When looking at a published REC/PR/WD it would often be useful to identify which commit it corresponds to.  One scenario is doing a diff between two published versions or between the current HEAD and the last WD or whatever.

This is nearly supported by ivoatex as it stands: as per [sec 3.8](https://www.ivoa.net/documents/Notes/IVOATexDoc/20230627/NOTE-ivoatexDoc-1.4-20230627.html#tth_sEc3.8) if you write `\input gitmeta` in the source, then some text like:
```
Version Control
    Revision 9562355, last change 2024-10-02 12:01:06 +0200
```
will appear in the generated PDF or HTML document.  But unfortunately (as in the above case taken from [REC-RegTAP-1.2](https://www.ivoa.net/documents/RegTAP/20241002/)) the commit hash often ends up not being visible in the checked out repository, since it's on a branch which ends up disappearing (it's not on the master/main).  This is likely to happen if you follow the instructions in [sec 3.12](https://www.ivoa.net/documents/Notes/IVOATexDoc/20230627/NOTE-ivoatexDoc-1.4-20230627.html#tth_sEc3.12) about how to prepare and submit a document release for publication.

One way to fix this would therefore be to modify the instructions in Sec 3.12 to make sure that the publication commit ends up on master/main; that's somewhat complicated because of the recommended PullRequest-based workflow, though not impossible if some rebasing is done.  But a better alternative might just be to recommend that a named tag with the obvious name (e.g. "REC-RegTAP-1.2") is pushed to the repository once the publish has been done, by whoever has permissions to do that.  This could be done after the fact (e.g. now, for all published document versions that we care about).

**Comment by msdemlei** [comment]
If you're happy with what PR #44 does, would you close this bug?

**Comment by mbtaylor** [comment]
Thanks Markus.
